// fauxx-desktop: Fauxx Desktop Companion
// Copyright (C) 2026 Digital Grease
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
// details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Device identity and the authenticated sealed channel.
//!
//! Each device owns a long-lived X25519 keypair generated by `dryoc` (the same
//! curve and box construction libsodium uses, so the Android side, issue E13,
//! interoperates byte-for-byte). The public half is shared out of band through
//! the pairing QR and over the mDNS TXT record; the secret half never leaves
//! this module's [`DeviceIdentity`] and is zeroized on drop.
//!
//! Every persona payload is sealed with authenticated public-key crypto_box
//! (X25519 key agreement, XSalsa20-Poly1305 AEAD): the sender signs with its
//! own secret key and the recipient's public key, so an unpaired peer can
//! neither read nor forge a message. We use authenticated `crypto_box_easy`
//! rather than an anonymous `sealed_box` precisely because "an unpaired peer
//! cannot sync" requires sender authentication: the open step verifies the MAC
//! against a *known, paired* sender public key, and a message from an unknown
//! key fails to authenticate. A fresh random nonce is drawn per message and
//! shipped alongside the ciphertext (the nonce is not secret; reusing one
//! under a fixed key pair would be the cryptographic failure, so it is never
//! reused).

use dryoc::classic::crypto_box::{
    crypto_box_easy, crypto_box_keypair, crypto_box_open_easy, Nonce, PublicKey, SecretKey,
};
use dryoc::constants::{
    CRYPTO_BOX_MACBYTES, CRYPTO_BOX_NONCEBYTES, CRYPTO_BOX_PUBLICKEYBYTES,
    CRYPTO_BOX_SECRETKEYBYTES,
};
use dryoc::rng::copy_randombytes;
use zeroize::Zeroize;

use crate::error::{CoreError, Result};

/// Length, in bytes, of an X25519 public key (32).
pub const PUBLIC_KEY_LEN: usize = CRYPTO_BOX_PUBLICKEYBYTES;
/// Length, in bytes, of an X25519 secret key (32).
pub const SECRET_KEY_LEN: usize = CRYPTO_BOX_SECRETKEYBYTES;
/// Length, in bytes, of a crypto_box nonce (24).
pub const NONCE_LEN: usize = CRYPTO_BOX_NONCEBYTES;
/// Length, in bytes, of the Poly1305 authentication tag (16).
pub const MAC_LEN: usize = CRYPTO_BOX_MACBYTES;

/// A device's long-lived X25519 secret key, zeroized on drop.
///
/// Held privately inside [`DeviceIdentity`]; the raw bytes are never exposed
/// through any public API, `Debug`, or log. `Debug` is implemented by hand to
/// redact the contents.
struct SecretKeyMaterial {
    bytes: SecretKey,
}

impl SecretKeyMaterial {
    fn as_bytes(&self) -> &SecretKey {
        &self.bytes
    }
}

impl Drop for SecretKeyMaterial {
    fn drop(&mut self) {
        self.bytes.zeroize();
    }
}

impl std::fmt::Debug for SecretKeyMaterial {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("SecretKeyMaterial(redacted)")
    }
}

/// This device's long-lived pairing identity: an X25519 keypair.
///
/// The public key is freely shareable (QR, mDNS TXT). The secret key is held
/// only here and scrubbed on drop. `Debug` redacts the secret.
#[derive(Debug)]
pub struct DeviceIdentity {
    public_key: PublicKey,
    secret_key: SecretKeyMaterial,
}

impl DeviceIdentity {
    /// Generate a fresh device identity from the OS CSPRNG.
    pub fn generate() -> Self {
        let (public_key, secret_key) = crypto_box_keypair();
        Self {
            public_key,
            secret_key: SecretKeyMaterial { bytes: secret_key },
        }
    }

    /// Reconstruct an identity from persisted key bytes (loaded from the OS
    /// keystore). Rejects wrong-length input by failing closed rather than
    /// padding or truncating.
    pub fn from_bytes(public_key: &[u8], secret_key: &[u8]) -> Result<Self> {
        let public_key: PublicKey = public_key.try_into().map_err(|_| {
            CoreError::Key(format!(
                "device public key is {} bytes, expected {PUBLIC_KEY_LEN}",
                public_key.len()
            ))
        })?;
        let secret_key: SecretKey = secret_key.try_into().map_err(|_| {
            CoreError::Key(format!(
                "device secret key is {} bytes, expected {SECRET_KEY_LEN}",
                secret_key.len()
            ))
        })?;
        Ok(Self {
            public_key,
            secret_key: SecretKeyMaterial { bytes: secret_key },
        })
    }

    /// This device's public key (safe to share).
    pub fn public_key(&self) -> &PublicKey {
        &self.public_key
    }

    /// Borrow the raw secret-key bytes for persistence into the OS keystore
    /// only. Crate-private so no public API, `Debug`, or log can reach it.
    pub(crate) fn secret_key_bytes(&self) -> &SecretKey {
        self.secret_key.as_bytes()
    }

    /// Seal `plaintext` for `recipient_public_key`, authenticated as coming
    /// from this device. Returns a self-describing [`SealedEnvelope`] carrying
    /// the fresh nonce and the ciphertext+MAC. An unpaired recipient cannot
    /// read it, and a third party cannot forge one without this device's
    /// secret key.
    pub fn seal(
        &self,
        recipient_public_key: &PublicKey,
        plaintext: &[u8],
    ) -> Result<SealedEnvelope> {
        let mut nonce: Nonce = [0u8; NONCE_LEN];
        copy_randombytes(&mut nonce);

        let mut ciphertext = vec![0u8; plaintext.len() + MAC_LEN];
        crypto_box_easy(
            &mut ciphertext,
            plaintext,
            &nonce,
            recipient_public_key,
            self.secret_key.as_bytes(),
        )
        .map_err(|e| CoreError::Sync(format!("seal failed: {e}")))?;

        Ok(SealedEnvelope { nonce, ciphertext })
    }

    /// Open a [`SealedEnvelope`] that `sender_public_key` sealed for this
    /// device. Authentication is checked against `sender_public_key`: a message
    /// from an unknown (unpaired) sender, or a tampered ciphertext, fails the
    /// MAC and returns an error. The caller is responsible for passing only a
    /// *paired* sender key here, which is what enforces "unpaired peers cannot
    /// sync".
    pub fn open(
        &self,
        sender_public_key: &PublicKey,
        envelope: &SealedEnvelope,
    ) -> Result<Vec<u8>> {
        if envelope.ciphertext.len() < MAC_LEN {
            return Err(CoreError::Sync("sealed envelope too short".to_string()));
        }
        let mut plaintext = vec![0u8; envelope.ciphertext.len() - MAC_LEN];
        crypto_box_open_easy(
            &mut plaintext,
            &envelope.ciphertext,
            &envelope.nonce,
            sender_public_key,
            self.secret_key.as_bytes(),
        )
        .map_err(|_| {
            CoreError::Sync(
                "sealed envelope failed authentication (forged, tampered, or unpaired sender)"
                    .to_string(),
            )
        })?;
        Ok(plaintext)
    }
}

/// A sealed persona payload: the per-message random nonce plus the
/// ciphertext (which already includes the trailing Poly1305 MAC).
///
/// This is the unit framed on the wire. It carries zero plaintext persona
/// fields; only the nonce (not secret) and the opaque ciphertext travel.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SealedEnvelope {
    /// The fresh per-message nonce (24 bytes). Public, never reused.
    pub nonce: Nonce,
    /// The crypto_box ciphertext, including the trailing 16-byte MAC.
    pub ciphertext: Vec<u8>,
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::error::Result;

    #[test]
    fn seal_open_round_trip() -> Result<()> {
        let alice = DeviceIdentity::generate();
        let bob = DeviceIdentity::generate();
        let message = b"persona payload bytes";

        // Alice seals for Bob; Bob opens, attributing it to Alice.
        let sealed = alice.seal(bob.public_key(), message)?;
        let opened = bob.open(alice.public_key(), &sealed)?;
        assert_eq!(opened, message);
        Ok(())
    }

    #[test]
    fn tampered_ciphertext_is_rejected() -> Result<()> {
        let alice = DeviceIdentity::generate();
        let bob = DeviceIdentity::generate();
        let mut sealed = alice.seal(bob.public_key(), b"hello")?;
        // Flip a bit in the ciphertext.
        sealed.ciphertext[0] ^= 0x01;
        assert!(matches!(
            bob.open(alice.public_key(), &sealed),
            Err(CoreError::Sync(_))
        ));
        Ok(())
    }

    #[test]
    fn tampered_nonce_is_rejected() -> Result<()> {
        let alice = DeviceIdentity::generate();
        let bob = DeviceIdentity::generate();
        let mut sealed = alice.seal(bob.public_key(), b"hello")?;
        sealed.nonce[0] ^= 0x01;
        assert!(matches!(
            bob.open(alice.public_key(), &sealed),
            Err(CoreError::Sync(_))
        ));
        Ok(())
    }

    #[test]
    fn unpaired_peer_cannot_open() -> Result<()> {
        let alice = DeviceIdentity::generate();
        let bob = DeviceIdentity::generate();
        let eve = DeviceIdentity::generate();
        let sealed = alice.seal(bob.public_key(), b"secret")?;
        // Eve was never the recipient: she cannot open it even attributing to
        // Alice (she lacks Bob's secret key).
        assert!(matches!(
            eve.open(alice.public_key(), &sealed),
            Err(CoreError::Sync(_))
        ));
        Ok(())
    }

    #[test]
    fn unpaired_peer_cannot_forge() -> Result<()> {
        let bob = DeviceIdentity::generate();
        let eve = DeviceIdentity::generate();
        let alice = DeviceIdentity::generate();
        // Eve seals a forgery for Bob, but Bob attributes incoming messages to
        // the *paired* Alice. The MAC was computed under Eve<->Bob, so opening
        // against Alice's public key fails authentication.
        let forged = eve.seal(bob.public_key(), b"forged")?;
        assert!(matches!(
            bob.open(alice.public_key(), &forged),
            Err(CoreError::Sync(_))
        ));
        Ok(())
    }

    #[test]
    fn from_bytes_rejects_wrong_length() {
        assert!(DeviceIdentity::from_bytes(&[0u8; 10], &[0u8; 32]).is_err());
        assert!(DeviceIdentity::from_bytes(&[0u8; 32], &[0u8; 10]).is_err());
    }

    #[test]
    fn round_trip_through_bytes_preserves_keys() -> Result<()> {
        let alice = DeviceIdentity::generate();
        let pk = *alice.public_key();
        let sk = *alice.secret_key_bytes();
        let restored = DeviceIdentity::from_bytes(&pk, &sk)?;
        assert_eq!(restored.public_key(), &pk);

        // The restored identity decrypts what the original could.
        let bob = DeviceIdentity::generate();
        let sealed = bob.seal(&pk, b"for the persisted identity")?;
        let opened = restored.open(bob.public_key(), &sealed)?;
        assert_eq!(opened, b"for the persisted identity");
        Ok(())
    }

    /// Cross-implementation interop GOLDEN VECTOR (C1 #7 / Android E13).
    ///
    /// Mints a deterministic `crypto_box` vector with FIXED keys and a FIXED
    /// nonce (so it is reproducible byte-for-byte by any libsodium-compatible
    /// implementation, e.g. lazysodium on Android), prints it in a
    /// copy-pasteable block (`cargo test ... -- --nocapture`), and asserts the
    /// round-trip plus the frozen contract constants the Android side froze
    /// against. Run with:
    ///   cargo test -p fauxx-core --lib sync::crypto::tests::interop_golden_vector_for_android_e13 -- --nocapture
    #[test]
    fn interop_golden_vector_for_android_e13() -> Result<()> {
        use base64::engine::general_purpose::URL_SAFE_NO_PAD;
        use base64::Engine as _;
        use dryoc::classic::crypto_core::crypto_scalarmult_base;

        let hex = |b: &[u8]| -> String { b.iter().map(|x| format!("{x:02x}")).collect() };

        // --- fixed inputs ---
        let sk_sender: SecretKey = [11u8; 32];
        let sk_recipient: SecretKey = [22u8; 32];
        let mut pk_sender: PublicKey = [0u8; 32];
        let mut pk_recipient: PublicKey = [0u8; 32];
        crypto_scalarmult_base(&mut pk_sender, &sk_sender);
        crypto_scalarmult_base(&mut pk_recipient, &sk_recipient);
        let nonce: Nonce = [0x55u8; NONCE_LEN];

        // --- plaintext: the real SyncMessage(PersonaUpsert) JSON ---
        let persona = crate::SyntheticPersona::new(
            "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa".to_string(),
            "Round Trip".to_string(),
            "AGE_35_44".to_string(),
            "TEACHER".to_string(),
            "CANADA".to_string(),
            vec!["ACADEMIC".to_string(), "HISTORY".to_string()],
            1_700_000_000_000,
            1_800_000_000_000,
        );
        let plaintext =
            crate::sync::wire::SyncMessage::persona_upsert(persona.clone()).to_plaintext()?;
        let plaintext_str =
            String::from_utf8(plaintext.clone()).map_err(|e| CoreError::Sync(e.to_string()))?;

        // --- seal with the FIXED nonce (low-level, NOT DeviceIdentity::seal) ---
        let mut ciphertext = vec![0u8; plaintext.len() + MAC_LEN];
        crypto_box_easy(
            &mut ciphertext,
            &plaintext,
            &nonce,
            &pk_recipient,
            &sk_sender,
        )
        .map_err(|e| CoreError::Sync(format!("seal: {e}")))?;

        // --- frames ---
        let frame = crate::sync::SealedFrame {
            envelope: SealedEnvelope {
                nonce,
                ciphertext: ciphertext.clone(),
            },
        }
        .to_bytes();
        let frame_len =
            u32::try_from(frame.len()).map_err(|_| CoreError::Sync("frame too large".into()))?;
        let mut tcp = frame_len.to_be_bytes().to_vec();
        tcp.extend_from_slice(&frame);

        // --- confirm opening with recipient secret + sender public recovers it ---
        let mut opened = vec![0u8; ciphertext.len() - MAC_LEN];
        crypto_box_open_easy(&mut opened, &ciphertext, &nonce, &pk_sender, &sk_recipient)
            .map_err(|e| CoreError::Sync(format!("open: {e}")))?;
        assert_eq!(opened, plaintext, "open must recover the sealed plaintext");
        let back = crate::sync::wire::SyncMessage::from_plaintext(&opened)?;
        if let crate::sync::SyncBody::PersonaUpsert(p) = back.body {
            assert_eq!(p.id, persona.id);
            assert_eq!(p.active_until, persona.active_until);
        } else {
            return Err(CoreError::Sync("expected PersonaUpsert".into()));
        }

        // --- (2) fingerprint vectors the Android side pinned ---
        let fp9 = crate::sync::fingerprint(&[9u8; 32]);
        let fp7 = crate::sync::fingerprint(&[7u8; 32]);
        let fp11 = crate::sync::fingerprint(&[11u8; 32]);
        assert_eq!(fp9, "25d8:0d45:a11b:372d");
        assert_eq!(fp7, "17cd:c7bc:a3f2:a0bd");
        assert_eq!(fp11, "2508:177e:3f55:3ec0");

        // --- (3) contract-drift assertions ---
        assert_eq!(crate::sync::DEFAULT_SYNC_PORT, 45_999);
        assert_eq!(crate::sync::SERVICE_TYPE, "_fauxx-sync._tcp.local.");
        assert_eq!(crate::sync::wire::TXT_KEY_VERSION, "v");
        assert_eq!(crate::sync::wire::TXT_KEY_FINGERPRINT, "fp");
        assert_eq!(crate::sync::wire::TXT_KEY_PUBKEY, "pk");
        assert_eq!(&frame[..4], b"FXS1");
        assert_eq!(&frame[4..6], &1u16.to_le_bytes());
        assert!(plaintext_str.contains("\"protocolVersion\":1"));
        assert!(plaintext_str.contains("\"kind\":\"PersonaUpsert\""));
        assert!(plaintext_str.contains("\"ageRange\":\"AGE_35_44\""));
        assert!(plaintext_str.contains("\"activeUntil\":1800000000000"));
        // frame from_bytes rejects: too short (< 46), bad magic, version > 1.
        assert!(crate::sync::SealedFrame::from_bytes(&[0u8; 45]).is_err());
        let mut bad_magic = frame.clone();
        bad_magic[0] = b'X';
        assert!(crate::sync::SealedFrame::from_bytes(&bad_magic).is_err());
        let mut bad_ver = frame.clone();
        bad_ver[4] = 2;
        assert!(crate::sync::SealedFrame::from_bytes(&bad_ver).is_err());
        // Frozen QR pairing vector: decodes to the expected fields, and the
        // encoder reproduces the exact frozen string (codec stability).
        const FROZEN_QR: &str = "eyJ2IjoxLCJuYW1lIjoiRGVza3RvcC1TdHVkeSIsInBrIjoiQndjSEJ3Y0hCd2NIQndjSEJ3Y0hCd2NIQndjSEJ3Y0hCd2NIQndjSEJ3YyIsImhvc3QiOiJkZXNrdG9wLmxvY2FsLiIsInBvcnQiOjQ1OTk5fQ";
        let payload = crate::sync::PairingPayload::decode(FROZEN_QR)?;
        assert_eq!(payload.name, "Desktop-Study");
        assert_eq!(payload.host.as_deref(), Some("desktop.local."));
        assert_eq!(payload.port, 45_999);
        assert_eq!(crate::sync::decode_public_key(&payload.pk)?, [7u8; 32]);
        let canonical = crate::sync::PairingPayload::new(
            "Desktop-Study".to_string(),
            &[7u8; 32],
            Some("desktop.local.".to_string()),
            45_999,
        )
        .encode()?;
        assert_eq!(
            canonical, FROZEN_QR,
            "QR pairing encoder drifted from the frozen vector"
        );

        // --- self-consistency of the emitted vector (the Android side pins it) ---
        let nonce_hex = hex(&nonce);
        let plaintext_hex = hex(&plaintext);
        let ciphertext_hex = hex(&ciphertext);
        let frame_hex = hex(&frame);
        let tcp_hex = hex(&tcp);
        let len_hex = hex(&frame_len.to_be_bytes());
        // (1) plaintext_hex decodes to the exact SyncMessage JSON bytes.
        assert_eq!(plaintext, plaintext_str.as_bytes());
        // (2) ciphertext = plaintext + the 16-byte Poly1305 MAC.
        assert_eq!(ciphertext.len(), plaintext.len() + MAC_LEN);
        // (3) FXS1 frame = "FXS1"(46585331) + u16 LE version(0100) + nonce + ciphertext.
        assert_eq!(
            frame_hex,
            format!("465853310100{nonce_hex}{ciphertext_hex}")
        );
        // (4) TCP frame = u32 BE frame length, then the frame.
        assert_eq!(tcp_hex, format!("{len_hex}{frame_hex}"));
        // (5) re-sealing with the same fixed nonce reproduces the ciphertext.
        let mut ciphertext2 = vec![0u8; plaintext.len() + MAC_LEN];
        crypto_box_easy(
            &mut ciphertext2,
            &plaintext,
            &nonce,
            &pk_recipient,
            &sk_sender,
        )
        .map_err(|e| CoreError::Sync(format!("re-seal: {e}")))?;
        assert_eq!(
            ciphertext2, ciphertext,
            "re-seal must reproduce the ciphertext"
        );

        // Write the vector to a file when asked (FAUXX_INTEROP_VECTOR_OUT=path)
        // so the long hex lines cannot be mangled by terminal piping. JSON, all
        // string fields; public keys as both hex and base64url-no-pad.
        if let Ok(out_path) = std::env::var("FAUXX_INTEROP_VECTOR_OUT") {
            let doc = serde_json::json!({
                "sk_sender_hex": hex(&sk_sender),
                "pk_sender_hex": hex(&pk_sender),
                "pk_sender_b64url": URL_SAFE_NO_PAD.encode(pk_sender),
                "sk_recipient_hex": hex(&sk_recipient),
                "pk_recipient_hex": hex(&pk_recipient),
                "pk_recipient_b64url": URL_SAFE_NO_PAD.encode(pk_recipient),
                "nonce_hex": nonce_hex,
                "plaintext_json": plaintext_str,
                "plaintext_hex": plaintext_hex,
                "ciphertext_hex": ciphertext_hex,
                "fxs1_frame_hex": frame_hex,
                "tcp_framed_hex": tcp_hex,
            });
            let body =
                serde_json::to_string_pretty(&doc).map_err(|e| CoreError::Sync(e.to_string()))?;
            std::fs::write(&out_path, body).map_err(|e| CoreError::Sync(e.to_string()))?;
        }

        // --- emit the copy-pasteable vector for the Android side ---
        println!("==== FAUXX E13 CRYPTO INTEROP GOLDEN VECTOR ====");
        println!("sk_sender_hex       = {}", hex(&sk_sender));
        println!(
            "pk_sender_b64url    = {}",
            URL_SAFE_NO_PAD.encode(pk_sender)
        );
        println!("sk_recipient_hex    = {}", hex(&sk_recipient));
        println!(
            "pk_recipient_b64url = {}",
            URL_SAFE_NO_PAD.encode(pk_recipient)
        );
        println!("nonce_hex           = {}", hex(&nonce));
        println!("plaintext_json      = {plaintext_str}");
        println!("plaintext_hex       = {}", hex(&plaintext));
        println!("ciphertext_hex      = {}", hex(&ciphertext));
        println!("fxs1_frame_hex      = {}", hex(&frame));
        println!("tcp_framed_hex      = {}", hex(&tcp));
        println!("fingerprint_9x32    = {fp9}");
        println!("fingerprint_7x32    = {fp7}");
        println!("fingerprint_11x32   = {fp11}");
        println!("==== END VECTOR ====");
        Ok(())
    }

    #[test]
    fn secret_debug_is_redacted() {
        let id = DeviceIdentity::generate();
        let rendered = format!("{id:?}");
        // The secret bytes must not appear; the redaction marker must.
        assert!(rendered.contains("redacted"));
    }
}
