// fauxx-desktop: Fauxx Desktop Companion
// Copyright (C) 2026 Digital Grease
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU Affero General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but WITHOUT
// ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
// FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more
// details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

//! Broker opt-out submission model, deadline tracking, and re-listing detection
//! (C3 #15, D1c).
//!
//! A [`FilledRequest`] is generated from a [`BrokerTemplate`] plus a persona's
//! details: the broker's required fields are filled from what we know about the
//! persona, and any field we cannot fill is reported as missing (generation is
//! solid and hermetic-testable; it never silently drops a required field).
//!
//! A [`BrokerSubmission`] is the persisted lifecycle record:
//! `drafted -> submitted -> confirmed -> removed`, with `relisted` re-opening a
//! removed record when the broker re-lists the persona. The
//! [`BrokerSubmission::is_deadline_due`] predicate drives reminders for
//! submissions still outstanding past their broker deadline.
//!
//! Re-listing detection is abstracted behind the [`ListingCheck`] trait so the
//! re-scan is hermetic-testable (tests inject results via [`StaticListingCheck`]);
//! the live implementation queries the decoy browser.

use std::collections::BTreeMap;

use async_trait::async_trait;
use serde::{Deserialize, Serialize};

use crate::brokers::registry::{BrokerTemplate, OptOutMethod, RequiredField};
use crate::error::Result;
use crate::persona::SyntheticPersona;

/// Milliseconds in one day, for deadline math over epoch-millis timestamps.
const MILLIS_PER_DAY: i64 = 24 * 60 * 60 * 1000;

/// The lifecycle status of a broker opt-out submission.
///
/// `drafted` -> `submitted` -> `confirmed` -> `removed` is the happy path;
/// `relisted` is set by the re-scan when a previously-`removed` persona is
/// detected on the broker again, flagging it for resubmission.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SubmissionStatus {
    /// The request has been generated/filled but not yet sent.
    Drafted,
    /// The request has been submitted to the broker (form posted / email sent).
    Submitted,
    /// The broker confirmed receipt (e.g. the emailed removal link was clicked).
    Confirmed,
    /// The broker actioned the request: the listing is gone.
    Removed,
    /// A previously-removed listing has re-appeared; needs resubmission.
    Relisted,
}

impl SubmissionStatus {
    /// The stored string form (matches the serde representation).
    pub fn as_str(&self) -> &'static str {
        match self {
            SubmissionStatus::Drafted => "drafted",
            SubmissionStatus::Submitted => "submitted",
            SubmissionStatus::Confirmed => "confirmed",
            SubmissionStatus::Removed => "removed",
            SubmissionStatus::Relisted => "relisted",
        }
    }

    /// Parse the stored string form back into a status.
    pub fn parse_str(s: &str) -> Option<Self> {
        match s {
            "drafted" => Some(SubmissionStatus::Drafted),
            "submitted" => Some(SubmissionStatus::Submitted),
            "confirmed" => Some(SubmissionStatus::Confirmed),
            "removed" => Some(SubmissionStatus::Removed),
            "relisted" => Some(SubmissionStatus::Relisted),
            _ => None,
        }
    }

    /// Whether this status is still "outstanding": the broker has not yet
    /// actioned the request, so a deadline can lapse. `removed` is settled;
    /// `relisted` is outstanding again (it needs a fresh submission).
    pub fn is_outstanding(&self) -> bool {
        matches!(
            self,
            SubmissionStatus::Drafted | SubmissionStatus::Submitted | SubmissionStatus::Relisted
        )
    }
}

/// A filled opt-out request for one `(broker, persona)`: the template plus the
/// concrete field values, ready to drive a web form or compose an email.
///
/// Generated by [`FilledRequest::generate`]. Any required field that could not
/// be filled from the persona is listed in [`missing_fields`](Self::missing_fields)
/// so the caller can prompt for it rather than silently submitting a partial
/// form. The generation itself never fails and never invents data.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct FilledRequest {
    /// The broker id this request targets.
    pub broker_id: String,
    /// The persona id this request is for.
    pub persona_id: String,
    /// The PUBLIC opt-out URL (copied from the template for convenience).
    pub opt_out_url: String,
    /// How this request is submitted (web-form / email / manual).
    pub method: OptOutMethod,
    /// The filled field values, keyed by the field key (see
    /// [`RequiredField::key`]). Deterministic order via `BTreeMap`.
    pub fields: BTreeMap<String, String>,
    /// Required fields that could NOT be filled from the persona; the caller
    /// must supply these before a real submission.
    pub missing_fields: Vec<String>,
}

impl FilledRequest {
    /// Generate a filled request for `template`/`persona`, plus optional
    /// caller-supplied `overrides` (e.g. a real confirmation email or a known
    /// listing URL the persona record does not carry).
    ///
    /// Field sourcing, in priority order: an explicit `overrides` value, then a
    /// value derivable from the persona (name, region-as-location), else the
    /// field is recorded as missing. Generation is deterministic and never
    /// errors: a fully-unfillable request still returns, with every unfilled
    /// required field reported in [`missing_fields`](Self::missing_fields).
    pub fn generate(
        broker_id: &str,
        template: &BrokerTemplate,
        persona: &SyntheticPersona,
        overrides: &BTreeMap<String, String>,
    ) -> Self {
        let mut fields = BTreeMap::new();
        let mut missing = Vec::new();

        for field in &template.required_fields {
            let key = field.key();
            // 1) Caller override always wins (and can fill any field, incl.
            //    Other(_) custom fields a broker may add).
            if let Some(value) = overrides.get(key).filter(|v| !v.trim().is_empty()) {
                fields.insert(key.to_string(), value.clone());
                continue;
            }
            // 2) Derive from the persona where we sensibly can.
            let derived = match field {
                RequiredField::Name => Some(persona.name.clone()),
                // The persona's region is the best location signal we hold; the
                // caller can override with a precise city/state.
                RequiredField::Location => Some(persona.region.clone()),
                // We never invent a listing URL, an email, or a phone number:
                // those are real contact/listing details the caller supplies.
                RequiredField::ListingUrl
                | RequiredField::Email
                | RequiredField::Phone
                | RequiredField::Other(_) => None,
            }
            .filter(|v| !v.trim().is_empty());

            match derived {
                Some(value) => {
                    fields.insert(key.to_string(), value);
                }
                None => missing.push(key.to_string()),
            }
        }

        FilledRequest {
            broker_id: broker_id.to_string(),
            persona_id: persona.id.clone(),
            opt_out_url: template.opt_out_url.clone(),
            method: template.method,
            fields,
            missing_fields: missing,
        }
    }

    /// Whether every required field is filled (no missing fields).
    pub fn is_complete(&self) -> bool {
        self.missing_fields.is_empty()
    }
}

/// A persisted broker opt-out submission record (C3 #15).
///
/// One row per `(broker, persona)` opt-out attempt, tracked through its
/// lifecycle. Persisted in the `broker_submissions` table; the
/// [`crate::store::EncryptedStore`] round-trips this whole record.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct BrokerSubmission {
    /// Stable id for this submission (UUID v4 string).
    pub id: String,
    /// The broker id this submission targets.
    pub broker_id: String,
    /// The persona id this submission is for.
    pub persona_id: String,
    /// Epoch milliseconds when the submission was recorded.
    pub submitted_at: i64,
    /// Current lifecycle status.
    pub status: SubmissionStatus,
    /// A broker-issued confirmation token (e.g. from a confirmation email), if
    /// any. Set when the broker confirms.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub confirmation_token: Option<String>,
    /// Epoch milliseconds by which the broker is expected to action the request
    /// (submitted_at + broker deadline window). Reminders fire past this when
    /// the submission is still outstanding.
    pub deadline: i64,
}

impl BrokerSubmission {
    /// Build a new submission record stamped `drafted`, computing the deadline
    /// from the broker template's actioning window.
    pub fn draft(
        id: String,
        broker_id: &str,
        persona_id: &str,
        template: &BrokerTemplate,
        submitted_at: i64,
    ) -> Self {
        Self {
            id,
            broker_id: broker_id.to_string(),
            persona_id: persona_id.to_string(),
            submitted_at,
            status: SubmissionStatus::Drafted,
            confirmation_token: None,
            deadline: submitted_at + template.deadline_days * MILLIS_PER_DAY,
        }
    }

    /// Whether this submission's deadline is due or overdue as of `now` AND the
    /// submission is still outstanding (so a settled `removed`/`confirmed`
    /// record does not generate a stale reminder). This is the reminder
    /// predicate the tracker uses to surface due/overdue opt-outs.
    pub fn is_deadline_due(&self, now: i64) -> bool {
        self.status.is_outstanding() && now >= self.deadline
    }

    /// Days remaining until the deadline as of `now` (negative when overdue).
    /// Truncates toward zero; purely for display.
    pub fn days_remaining(&self, now: i64) -> i64 {
        (self.deadline - now) / MILLIS_PER_DAY
    }
}

/// Outcome of a re-listing re-scan for one submission (C3 #15).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RelistOutcome {
    /// The submission that was re-scanned.
    pub submission_id: String,
    /// The broker id checked.
    pub broker_id: String,
    /// Whether the persona was found still/again listed on the broker.
    pub still_listed: bool,
    /// Whether this scan FLIPPED a previously-removed record to `relisted`.
    pub newly_relisted: bool,
}

/// The seam for "is this persona still listed on this broker" (C3 #15).
///
/// Abstracted behind a trait so re-listing detection is hermetic-testable:
/// tests inject deterministic results via [`StaticListingCheck`]. The
/// browser-backed live implementation (which would drive the decoy browser to a
/// broker's PUBLIC search/listing page and parse presence) is DEFERRED to a
/// later broker-scan issue; this issue ships the trait, the pure transition
/// logic, and the hermetic check. `async_trait` because the live check is an
/// async browser navigation.
#[async_trait]
pub trait ListingCheck: Send + Sync {
    /// Whether `persona` currently appears listed on the broker identified by
    /// `broker_id`. The live implementation navigates the decoy browser to the
    /// broker's PUBLIC listing/search page (guarded), never an account.
    async fn is_listed(&self, broker_id: &str, persona: &SyntheticPersona) -> Result<bool>;
}

/// A deterministic [`ListingCheck`] for hermetic tests: it returns a fixed
/// "listed" verdict per broker id (defaulting to "not listed" for ids absent
/// from the map). No browser, no network.
#[derive(Debug, Clone, Default)]
pub struct StaticListingCheck {
    listed_by_broker: BTreeMap<String, bool>,
}

impl StaticListingCheck {
    /// An empty check that reports every broker as "not listed".
    pub fn new() -> Self {
        Self::default()
    }

    /// Set the "listed" verdict for a broker id (builder style).
    pub fn with_listed(mut self, broker_id: &str, listed: bool) -> Self {
        self.listed_by_broker.insert(broker_id.to_string(), listed);
        self
    }
}

#[async_trait]
impl ListingCheck for StaticListingCheck {
    async fn is_listed(&self, broker_id: &str, _persona: &SyntheticPersona) -> Result<bool> {
        Ok(self
            .listed_by_broker
            .get(broker_id)
            .copied()
            .unwrap_or(false))
    }
}

/// Compute the re-listing transition for a submission given a "still listed"
/// verdict (C3 #15). Pure decision logic, separated from I/O so it is directly
/// unit-testable: a previously-`removed` submission found listed again FLIPS to
/// `relisted` (newly_relisted = true). Returns the new status to persist, or
/// `None` when no change is warranted.
pub fn relist_transition(
    current: SubmissionStatus,
    still_listed: bool,
) -> Option<SubmissionStatus> {
    match (current, still_listed) {
        // The core re-listing case: a removed record re-appears.
        (SubmissionStatus::Removed, true) => Some(SubmissionStatus::Relisted),
        // Everything else: no transition from a re-scan alone. We deliberately do
        // NOT auto-mark anything `removed` from a "not listed" scan; confirmation
        // of removal is a tracked status set explicitly.
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::brokers::registry::broker;
    use crate::persona::{AgeRange, CategoryPool, Profession, Region};

    fn persona() -> SyntheticPersona {
        SyntheticPersona::new(
            "broker-test-0000-4000-8000-000000000000".to_string(),
            "Jordan Rivera".to_string(),
            AgeRange::AGE_35_44.as_name().to_string(),
            Profession::ENGINEER.as_name().to_string(),
            Region::US_WEST.as_name().to_string(),
            vec![
                CategoryPool::TECHNOLOGY.as_name().to_string(),
                CategoryPool::SCIENCE.as_name().to_string(),
                CategoryPool::TRAVEL.as_name().to_string(),
            ],
            1_700_000_000_000,
            1_700_600_000_000,
        )
    }

    #[test]
    fn generate_fills_persona_fields_and_reports_missing() -> Result<()> {
        // Spokeo needs listing_url + email; neither is derivable from a persona.
        let t = broker("spokeo")?;
        let req = FilledRequest::generate("spokeo", t, &persona(), &BTreeMap::new());
        assert_eq!(req.broker_id, "spokeo");
        assert_eq!(req.persona_id, persona().id);
        assert_eq!(req.opt_out_url, t.opt_out_url);
        // Both required fields are unfillable from a persona alone.
        assert!(req.fields.is_empty());
        assert!(req.missing_fields.contains(&"listing_url".to_string()));
        assert!(req.missing_fields.contains(&"email".to_string()));
        assert!(!req.is_complete());
        Ok(())
    }

    #[test]
    fn generate_fills_name_and_location_from_persona() -> Result<()> {
        // BeenVerified needs name + location + email; name/location derive from
        // the persona, email is supplied via overrides.
        let t = broker("beenverified")?;
        let mut overrides = BTreeMap::new();
        overrides.insert("email".to_string(), "decoy@example.test".to_string());
        let req = FilledRequest::generate("beenverified", t, &persona(), &overrides);
        assert_eq!(
            req.fields.get("name").map(String::as_str),
            Some("Jordan Rivera")
        );
        assert_eq!(
            req.fields.get("location").map(String::as_str),
            Some(Region::US_WEST.as_name())
        );
        assert_eq!(
            req.fields.get("email").map(String::as_str),
            Some("decoy@example.test")
        );
        assert!(req.is_complete(), "all required fields filled: {req:?}");
        Ok(())
    }

    #[test]
    fn overrides_take_priority_over_persona_derived() -> Result<()> {
        let t = broker("beenverified")?;
        let mut overrides = BTreeMap::new();
        overrides.insert("name".to_string(), "Override Name".to_string());
        overrides.insert("location".to_string(), "Seattle, WA".to_string());
        overrides.insert("email".to_string(), "x@example.test".to_string());
        let req = FilledRequest::generate("beenverified", t, &persona(), &overrides);
        assert_eq!(
            req.fields.get("name").map(String::as_str),
            Some("Override Name")
        );
        assert_eq!(
            req.fields.get("location").map(String::as_str),
            Some("Seattle, WA")
        );
        Ok(())
    }

    #[test]
    fn draft_computes_deadline_and_outstanding_starts_drafted() -> Result<()> {
        let t = broker("spokeo")?; // 30-day window
        let sub = BrokerSubmission::draft(
            "sub-1".to_string(),
            "spokeo",
            &persona().id,
            t,
            1_000_000_000_000,
        );
        assert_eq!(sub.status, SubmissionStatus::Drafted);
        assert_eq!(sub.deadline, 1_000_000_000_000 + 30 * MILLIS_PER_DAY);
        assert!(sub.confirmation_token.is_none());
        Ok(())
    }

    #[test]
    fn deadline_due_predicate_respects_status_and_time() -> Result<()> {
        let t = broker("spokeo")?;
        let start = 1_000_000_000_000;
        let mut sub = BrokerSubmission::draft("s".to_string(), "spokeo", "p", t, start);
        // Before the deadline: not due.
        assert!(!sub.is_deadline_due(start));
        assert!(!sub.is_deadline_due(sub.deadline - 1));
        // At/after the deadline while outstanding: due.
        assert!(sub.is_deadline_due(sub.deadline));
        assert!(sub.is_deadline_due(sub.deadline + MILLIS_PER_DAY));
        // A settled (removed) submission never generates a reminder, even overdue.
        sub.status = SubmissionStatus::Removed;
        assert!(!sub.is_deadline_due(sub.deadline + MILLIS_PER_DAY));
        // A relisted submission IS outstanding again.
        sub.status = SubmissionStatus::Relisted;
        assert!(sub.is_deadline_due(sub.deadline));
        // days_remaining is signed.
        assert_eq!(sub.days_remaining(start), 30);
        assert!(sub.days_remaining(sub.deadline + MILLIS_PER_DAY) < 0);
        Ok(())
    }

    #[test]
    fn relist_transition_only_flips_removed_to_relisted() {
        assert_eq!(
            relist_transition(SubmissionStatus::Removed, true),
            Some(SubmissionStatus::Relisted)
        );
        // Removed + not listed: still removed (no change).
        assert_eq!(relist_transition(SubmissionStatus::Removed, false), None);
        // A non-removed status is never auto-changed by a scan.
        assert_eq!(relist_transition(SubmissionStatus::Submitted, true), None);
        assert_eq!(relist_transition(SubmissionStatus::Drafted, true), None);
        assert_eq!(relist_transition(SubmissionStatus::Relisted, true), None);
    }

    #[tokio::test]
    async fn static_listing_check_injects_results() -> Result<()> {
        let check = StaticListingCheck::new()
            .with_listed("spokeo", true)
            .with_listed("whitepages", false);
        let p = persona();
        assert!(check.is_listed("spokeo", &p).await?);
        assert!(!check.is_listed("whitepages", &p).await?);
        // Unknown broker defaults to not listed.
        assert!(!check.is_listed("unknown", &p).await?);
        Ok(())
    }

    #[test]
    fn status_string_round_trips() {
        for s in [
            SubmissionStatus::Drafted,
            SubmissionStatus::Submitted,
            SubmissionStatus::Confirmed,
            SubmissionStatus::Removed,
            SubmissionStatus::Relisted,
        ] {
            assert_eq!(SubmissionStatus::parse_str(s.as_str()), Some(s));
        }
        assert_eq!(SubmissionStatus::parse_str("garbage"), None);
    }
}
